### ISSUE TITLE
The master branch is different than the version on npm

### ISSUE THREAD

**Issue by Zestrial** [LinaTsukusu/youtube-chat#9]
I wanted to submit a fix to #8, but I couldn't import an unmodified fork of this repository. However, I could run the version pushed to npm.

After comparing the master branch and the npm package, I found that they were different. 

---

NPM version:

![image](https://user-images.githubusercontent.com/37517470/103159407-21584980-4797-11eb-8487-1a2f4c3381e5.png)

Master version:

![image](https://user-images.githubusercontent.com/37517470/103159420-3634dd00-4797-11eb-88c4-d9ce20a1f20f.png)

**Comment by nvlled** [comment]
AFAIK, you don't normally add the sources in the npm, just the bundled js files. You should run ```npm run build``` then import the files from the ./dist directory if you want to test your changes.

**Comment by Draguwro** [comment]
@nvlled When I installed `LinaTsukusu/youtube-chat#master` rather than `youtube-chat` using `yarn add`, I couldn't import the package in my code using `import {LiveChat} from "youtube-chat"`. I had to use `import {LiveChat} from "youtube-chat/src"`, and even when I used that, it still didn't work. 

It gave me this error:
```
import {LiveChat} from './live-chat'
       ^

SyntaxError: Unexpected token {
```

Also, there's no `./dist` directory in this branch, so I couldn't run `npm run build`.

**Comment by nvlled** [comment]
The ```./dist``` will be created if the build is successful and there are no errors.
I think node doesn't support ES modules yet, you have to use a bundler, or just do like this instead:
```const LiveChat = require("./youtube-chat").LiveChat;```
